<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admindeMacBook-Pro.local" failures="1" tests="6" name="Command line test" time="0.153" errors="0" timestamp="7 Jul 2020 11:27:02 GMT">
  <testcase classname="DemoTest" name="testEqual" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at DemoTest.testEqual(DemoTest.java:23)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testEqual -->
  <testcase classname="DemoTest" name="testEqual" time="0.001"/>
  <testcase classname="DemoTest" name="testEqual" time="0.0"/>
  <testcase classname="DemoTest" name="testEqual" time="0.0"/>
  <testcase classname="HttpDemo1Test" name="testHttp1" time="0.129"/>
  <testcase classname="HttpDemo1Test" name="testHttp1" time="0.002"/>
</testsuite> <!-- Command line test -->
